### ISSUE TITLE
As far as disorganized, this is king (of disorder)

### ISSUE THREAD

**Issue by WalterOkumu** [jamstack-cms/jamstack-ecommerce#36]
I honestly, have not seen a more disorganised piece of work.

I respect the thought that was pulling it together, but fundametally, you owe it to yourself to organise your code in a fashion that succeeds you as the developer.

As a mode to train, I would advise against using this, but this is a learning opportuntity for any developer out there.

Your code is your thoughts. Your thoughts are the base of which other developers build. Shit code leads to shit builds, and this is perfect in example.

I need to strip it all the way down to make it useful.

Note, I'm not being a pain for no reason, but anyone who organises their folders like this project deserves a beating

**Comment by WalterOkumu** [comment]
As I dig deeper it gets worse. Like, who writes code like this? Are you under duress??

**Comment by WalterOkumu** [comment]
Wow, this is just a purely terribly executed idea. The concept is great, but execution is as great as a shot in the head

**Comment by stav** [comment]
Wow, purely terribly?

I was really hoping to get some gems from a smart person. For example when I read, "As I dig deeper it gets worse. Like..."

I thought briefly, "oh great here's an example."

But then, "Like, who writes code like this?"

Disappointed sad face.

**Negative reviews** are great because we live in a time of **positive marketing**: 
 - Facebook friends only show you the good stuff about their lives,
 - product websites are also positive-only,
 - review videos rarely show anything negative,
 - forget advertisements, little value there.

Usually I only read the _negative reviews_ on Amazon.  4 out of 5 star reviews are the best because they tend to explain _that one small thing_ that kept them from giving it a five-star review.

We also live in a time of **solutions**.  Just complaining about how bad someone else's work is does not give me any information about the product.  If the complainer doesn't offer any solutions that to me says more about the complainer.  As if the complainer wants the world to think, "wow, this guy must be really smart."

People that want the world to _think they are smart_ usually think poorly of themselves.

The directory structure of this project is very similar to to other modern projects I see, RedwoodJS comes to mind.  I suppose you are talking about nesting code under `src` or organizing into `packages`; fair points. 

Hey you know, Walter, what about forking the repo and submitting a pull request; or, at least tell us the files you were looking at when you made these comments.

**Comment by WalterOkumu** [comment]
Apologies, I frustrated night of whisky and coding, didn't mean anything by it. 

I went through the code the following day and it's an great project. There's a lot of possibilities
